### ISSUE TITLE
Solana Pathway getter.ts "Unexpected 28 bytes after deserialized data"

### ISSUE THREAD

**Issue by tomashco** [figment-networks/learn-web3-dapp#210]
Hi everyone,
I'm doing the Solana Pathway and is really nice, but I found at lesson 10 a possible error in code due to borsh deserialize method:

if you use in getter the borsh.deserialize, as solution suggest:
```
    const greeting = borsh.deserialize(
      GreetingSchema,
      GreetingAccount,
      accountInfo.data,
    );
```
you will receive the following error:
"Unexpected 28 bytes after deserialized data"

I've digged inside the borsh code and actually this is because borsh.deserialize makes a check as follows:
```
/// Deserializes object from bytes using schema.
function deserialize(schema, classType, buffer) {
    const reader = new BinaryReader(buffer);
    const result = deserializeStruct(schema, classType, reader);
    if (reader.offset < buffer.length) {
        throw new BorshError(`Unexpected ${buffer.length - reader.offset} bytes after deserialized data`);
    }
    return result;
```

Reader offset is actually initialized at 4, thus it throws the error.

A short solution could be to use the method: deserializeUnchecked instaed of deserialize.

Do you know the reason for this behaviour?
Is there a way to use deserialize correctly?

thank you very much
Tom

**Comment by zurgl** [comment]
@tomashco Hello, we cannot reproduce this issue and it is the first time someone has reported it.
Could confirm you still experience this issue?
Could you join us on  [Discord](https://discord.com/invite/fszyM7K)?

Thanks
