### ISSUE TITLE
feat:  Turning this repo to monorepo and more.

### ISSUE THREAD

**Issue by Necmttn** [figment-networks/learn-web3-dapp#221]
### Dependency requirements.
Currently, we have every tutorial in the same app with origin single package JSON.  this concerns me because more and more tutorials we will add will have different version dependencies or maintenance burdens on us to keep updating the old tutorials. 

### Size of the initial install.
<img width="411" alt="Screenshot 2022-01-06 at 3 01 46 PM" src="https://user-images.githubusercontent.com/5212808/148349469-2c76233f-6e18-47c8-a485-caf6fbb71922.png">
Currently when brand new user arrive s/he needs to install about ~1.2 / ~1.3 GB node_modules. 

## Suggestion 
I think we can convert this project to [turborepo](https://turborepo.org/docs) with every pathway/tutorial is under a separate package. 

What's in my mind is more like next monorepo where 
https://github.com/vercel/next.js/tree/canary/examples 
![image](https://user-images.githubusercontent.com/5212808/148351467-07706318-0039-4c56-9fc5-747870e66936.png)
each example is separated from each others. if you are a generalist you can pull the whole [repo](https://github.com/vercel/next.js) and cd into example `yarn install & yarn dev` you are up and running. 

if you're more like have particular interest for singular pathway what you could do is.
```
npx create-learn-web3-dapp --pathway polygon-nft-101 polygon-nft-101
# or
yarn create-learn-web3-dapp --example polygon-nft-101 polygon-nft-101
```
with that, they will have a clean folder without any extra dependency and which they could extend as however, they wish.
For example: currently, we are writing a liquidation bot a person who learned it with a basic algorithm to trade, might wanna extend the project with a more complicated setup but it's so much complicated to write top of the tutorial at the moment. 

### Opportunity to develop a tiny sharable piece of utility code/component library.
As I started learning web3 I have noticed that I move a bunch of small code scripts around between projects for airdrop wallet to find the route for ens.  it would be cool if would separate this small logic in the monorepo package and published it to npm. I think we do have the potential to become https://github.com/streamich/react-use of the web3.

### CI/CD setup / testing.
Currently, we don't have much testing and I think we should but I'm also aware that's gonna be a pain. but once we have the packages are separated we could have OSS volunteers to improve our coverage. 

### Pathway progress to  CTF (capture the flag)  Gamifying a bit.
I understand the initial thoughts were when designing the pathway progress and steps to give learners a feeling of accomplishment & tracking the progress. This is cool but there's an even cooler option. I was fascinated with the idea [StarFigher project](https://www.kalzumeus.com/2015/03/09/announcing-starfighter/);

> Starfighter CTFs are not fantastic Hollywood-logic depictions of what programming is like. There is no “I built a GUI interface using Visual Basic to track the IP address.”
> You will use real technology. You will build real systems. You will face the real problems faced by the world’s best programmers building the world’s most important pieces of software.
> You will conquer those problems. You will prove yourself equal to the very best. Becoming a top Starfighter player is a direct path to receiving lucrative job offers from the best tech companies in the world because you’ll have proven beyond a shadow of a doubt that you can do the work these companies need to be done.
>WHAT IS A STARFIGHTER?
> We’re going to publish a game in the genre often described as “Capture The Flag” (CTF). It will be a goal-oriented exploration of technology.
> You will code to play. You will not pay to code.
>Our CTF will be totally free for players. (Not “free-to-play.” There is no catch. We will not ask you to pay extra to buy funny hats or recharge energy or unlock the full version.)
> To progress in the game, players will have to use every programming skill they know, and pick up new tricks along the way.

It is unfortunate the project was discontinued. I wanted to implement this a lot for my  [paircode.dev](https://paircode.dev) way of replacing the technical interviews but as you guys can imagine it's definitely not a single-man challenge. It makes more sense with the context of `Learn`. 

#### Making a difference between learning tutorial vs CTF. 
I think we should not change anything how tutorials have small challenges to progress. It's good as it's. what I'm suggesting is adding a little extra challenge where user gets a unique `flag` probably bound to their wallet signature. When they have the flag submitted to our central `program` we could reward them an NFT badge proving they have completed this tutorial and solved an extra puzzle. The reasoning making the `flag`s unique prevent people copy-pasting solutions around to collect a bunch of NFT badges without proving they are worthy. 
![image](https://user-images.githubusercontent.com/5212808/148357686-6e6a25a5-cb3c-44d3-aaf6-a4e8e29d14f0.png)
I like how Austin Griffith does in his speedrun eth course. 

#### Pathways !== tutorial/course
When I was working for ASU we built a Udemy like UI for students to sign up for courses and upon completing the course they would get awarded a badge from https://badgr.com/ (worst API I have worked IML) by their teachers. And in the application, we had an interface for users to see their progress based on their own goals. 
![image](https://user-images.githubusercontent.com/5212808/148360581-40521828-33e7-4b9d-8f39-df70db64ebed.png)
Pathways are more like the outcome users wants it can also include multiple courses/tutorial to finish one pathway. 
![image](https://user-images.githubusercontent.com/5212808/148362476-30b182d2-7ea9-4e47-bad1-cb15711f75e6.png)

let me know what you guys think @figment-networks/learn 
Cheers 🖖

**Comment by zurgl** [comment]
as this content is supposed to be migrated to Kafé, I close this one.
