### ISSUE TITLE
Small typo 

### ISSUE THREAD

**Issue by 0xShy101** [figment-networks/learn-web3-dapp#224]
Small typo in the "Connect" step in Secret Path

CosmWamClient => CosmWasmClient

![image](https://user-images.githubusercontent.com/79533966/148699816-a934efe9-759e-4ea4-82c3-a24ddfe3e285.png)

**Comment by zurgl** [comment]
@TheShy101 It will be more fun is you do the PR fixing it. Are you motivated enough to take over this?
Our goal as a community is to incentive the collaboration of our members, then raising issues is a good point opening a PR to fix it is the next step.

**Comment by 0xShy101** [comment]
@zurgl I have made a pull request #234

**Comment by zurgl** [comment]
@0xShy101 thanks
