### ISSUE TITLE
[Solana Pathway] Use `http` instead of `https` for localhost config cluster

### ISSUE THREAD

**Issue by andyyy60** [figment-networks/learn-web3-dapp#239]
Currently, the tutorial instructions outline that in order to target the localnet cluster the user must target `https://localhost:8899`

![image](https://user-images.githubusercontent.com/8968003/151711130-344a9bca-4d38-4c0d-8472-10394a4922d4.png)

If a user points to `https://localhost:8899` instead of `http://localhost:8899`, any subsequent request from Solana CLI will fail with error:
```error sending request for url (https://localhost:8899/): error trying to connect: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:```

This essentially is a TLS error caused by the inconsistency between HTTPS and HTTP protocols. 

Thankfully, this is an easy fix on file https://github.com/figment-networks/learn-web3-dapp/blob/main/markdown/solana/PROJECT_SETUP.md.

I'd do it myself but I do not have the right privileges to create branches. Took me a while to figure out this was the root cause of my deployment errors, hopefully it can get fixed!

**Comment by zurgl** [comment]
@andyyy60 Thanks for mentioning that point. Will be fixed soon
