### ISSUE TITLE
polygon step 6 has solution already filled in, and file name is incorrect

### ISSUE THREAD

**Issue by ahh1539** [figment-networks/learn-web3-dapp#247]
Hi all, looking to step 6 for the polygon path (making a transfer) the file meant to be edited to work already has filled in solutions as shown here: https://github.com/figment-networks/learn-web3-dapp/blob/main/components/protocols/polygon/challenges/transfer.ts

according to the step instructions, the file contents should instead look like this:

```
  try {
    const provider = new ethers.providers.Web3Provider(window.ethereum);
    const send_account = provider.getSigner().getAddress();

    const currentGasPrice = await provider.getGasPrice();
    const gas_price = ethers.utils.hexlify(
      parseInt(currentGasPrice.toString()),
    );

    const transaction = undefined;

    const hash = undefined;
    const receipt = await hash.wait();
    return {hash: receipt.transactionHash};
  }
```

Additionally, the file path to edit in the instructions is incorrect, currently, it is listed as:
`components/protocols/polygon/challenges/Transfer.tsx` 

the correct file path is: 
`components\protocols\polygon\challenges\transfer.ts`

**Comment by pyr0gan** [comment]
https://github.com/figment-networks/learn-web3-dapp/pull/246 and https://github.com/figment-networks/learn-web3-dapp/pull/254 fix this issue, thank you for reporting @ahh1539 😄
