### ISSUE TITLE
Desktop VSCode does not run the gitpod workspace correctly

### ISSUE THREAD

**Issue by LimitBreaker98** [figment-networks/learn-web3-dapp#265]
The option to open the gitpod on one's own VSCode does not work correctly. 

Once the app is running locally, upon trying to enter either the NEAR, SOLANA or the POLYGON pathways, a message similar to the following appears.

<img width="1192" alt="Screen Shot 2022-03-04 at 3 59 54 PM" src="https://user-images.githubusercontent.com/28995466/156840991-9b390e12-4e35-41d4-90a1-c9ff6fa1ba9b.png">

**Comment by pyr0gan** [comment]
@LimitBreaker98 👋 I will look at testing this, going forward. As far as I know, when using Gitpod, nothing should be running locally except for VSCode. It may be that the remote was not connected? Any additional context you can provide would be helpful.

**Comment by pyr0gan** [comment]
@LimitBreaker98 As of January 2023, I could not reproduce this issue in GitPod.
