### ISSUE TITLE
Solana pathway no "Next" button.

### ISSUE THREAD

**Issue by x-N0** [figment-networks/learn-web3-dapp#278]
![image](https://user-images.githubusercontent.com/51316342/174927097-565360e3-58ea-48bc-9208-47cfb061968c.png)
Not a big of a deal but the first page that is a how to says to click the "Next" button, but there's only a "Setup the Project" button.

**Comment by pyr0gan** [comment]
@x-N0 I've amended the PREFACE.md to mention the Setup button (see PR#282 : https://github.com/figment-networks/learn-web3-dapp/pull/282) 👍
