### ISSUE TITLE
Learn about Fuse

### ISSUE THREAD

**Issue by bertux** [figment-networks/learn-web3-dapp#280]
Hello,
would you be open to contribution about learning to use Fuse EVM blockchain in than the other EVM blockchains already covered ?

**Comment by pyr0gan** [comment]
@bertux Thanks for reaching out! The Learn team does not plan to add Fuse to `learn-web3-dapp` at this time. 

If you would like to add content, please fork the repo and make a pull request. If the content is to the existing standards of Figment Learn, we could look at merging it - provided that there are public RPC endpoints available.
