### ISSUE TITLE
Add Flow Path

### ISSUE THREAD

**Issue by muttoni** [figment-networks/learn-web3-dapp#288]
Hi, loving learn-web3-dapp!

Do you have plans to add Flow?

If not, is there a contribution guide I can follow and I can take a stab at it?

Thanks!

EDIT: I found some info from early August, but keeping this issue open in case the process has changed since then.

**Comment by pyr0gan** [comment]
@muttoni Thanks for your interest, we don't have plans to add any additional chains to this project.
