### ISSUE TITLE
Solana airdrop error

### ISSUE THREAD

**Issue by haowang1013** [figment-networks/learn-web3-dapp#38]
Hi,

I was following the solana tutorial and got an error when running the [airdrop step](https://learn.figment.io/tutorials/fund-solana-account).
The response from the rpc call is:
```
{
  jsonrpc: '2.0',
  error: { code: -32600, message: 'Invalid request' },
  id: 'a0509999-fb4f-4829-903a-d3e39ce499f7'
}
```

Any idea what could be causing this?

**Comment by guillaumegaluz** [comment]
Thanks for reporting! The Solana official faucet has been having intermittent issues...

@zurgl is this on our side in the faucet's side?

**Comment by zurgl** [comment]
@guillaumegaluz datahub doesn't provide airdrop functionality then we need for this step to rely on devent faucet. I've done the switch

**Comment by guillaumegaluz** [comment]
Sorry, i don't understand what you mean.

1) Is the Solana faucet still down? The Solana team told me it's back up.
2) What change did you make? "Switch" to what? Can you link a PR where a change has been made?

**Comment by haowang1013** [comment]
BTW, when I had this issue I was able to airdrop using the solana cli directly.
